# Generated by Django 3.2.7 on 2022-02-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='claimable',
            field=models.BooleanField(default=False),
        ),
    ]
