# Generated by Django 3.2.7 on 2021-09-22 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '0001_initial'),
        ('courier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Action_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tracking_id', models.CharField(max_length=50, null=True)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=100)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.courier')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.source')),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reason_Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.option')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.reason')),
            ],
            options={
                'unique_together': {('reason', 'option')},
            },
        ),
        migrations.CreateModel(
            name='Courier_Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.URLField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.courier')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.order')),
                ('created', models.DateField()),
                ('notes', models.CharField(max_length=255, null=True)),
                ('processed', models.DateField(null=True)),
                ('action_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.action_customer')),
                ('action_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.action_product')),
                ('reason_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.reason_option')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resend',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.order')),
                ('created', models.DateField()),
                ('notes', models.CharField(max_length=255, null=True)),
                ('picked', models.CharField(max_length=10)),
                ('packed', models.CharField(max_length=10)),
                ('dor', models.BooleanField()),
                ('processed', models.DateField(null=True)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.reason')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.order')),
                ('created', models.DateField()),
                ('notes', models.CharField(max_length=255, null=True)),
                ('full_refund', models.BooleanField()),
                ('amount', models.FloatField()),
                ('void', models.BooleanField()),
                ('dor', models.BooleanField()),
                ('processed', models.DateField(null=True)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.reason')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
