# Generated by Django 3.2.7 on 2021-09-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='resend',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.room'),
        ),
        migrations.AlterField(
            model_name='resend',
            name='packed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='WarehousePacker', to='order.warehouse'),
        ),
        migrations.AlterField(
            model_name='resend',
            name='picked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.warehouse'),
        ),
    ]
