# Generated by Django 3.2.7 on 2021-10-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210929_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='resend',
            name='pending',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
