# Generated by Django 3.2.7 on 2021-11-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_resend_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='resend',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='return',
            name='processed',
        ),
        migrations.CreateModel(
            name='Resend_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.resend')),
            ],
        ),
    ]
