# Generated by Django 3.2.7 on 2021-11-22 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20211108_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='action_product',
        ),
        migrations.CreateModel(
            name='ReturnItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('originalQty', models.IntegerField()),
                ('actionQty', models.IntegerField()),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.action_product')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.return')),
            ],
            options={
                'unique_together': {('order', 'sku')},
            },
        ),
    ]
