# Generated by Django 3.2.7 on 2021-11-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20211122_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnitems',
            old_name='action',
            new_name='action_product',
        ),
    ]
