# Generated by Django 3.2.7 on 2021-11-22 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_action_returnitems_action_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.return'),
        ),
    ]
