# Generated by Django 3.2.7 on 2021-11-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_returnitems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='order_total',
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
    ]
