# Generated by Django 3.2.7 on 2021-11-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_refund_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='void',
            new_name='void_order',
        ),
    ]
