# Generated by Django 3.2.7 on 2021-11-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_rename_void_refund_void_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='order_total',
        ),
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
