# Generated by Django 3.2.7 on 2021-11-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20211124_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnitems',
            old_name='actionQty',
            new_name='action_qty',
        ),
        migrations.RenameField(
            model_name='returnitems',
            old_name='originalQty',
            new_name='original_qty',
        ),
    ]
