# Generated by Django 3.2.7 on 2021-11-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20211124_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitems',
            name='title',
            field=models.CharField(default='ProductName', max_length=255),
            preserve_default=False,
        ),
    ]
