# Generated by Django 3.2.7 on 2021-12-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_returnitems_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
        migrations.AddField(
            model_name='refund',
            name='order_total',
            field=models.FloatField(default=4.45),
            preserve_default=False,
        ),
    ]
