# Generated by Django 3.2.7 on 2021-12-15 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0015_auto_20211213_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.order')),
                ('created', models.DateField()),
                ('notes', models.CharField(max_length=255, null=True)),
                ('dor', models.BooleanField()),
                ('pending', models.BooleanField()),
                ('packer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PendingPacker', to='order.warehouse')),
                ('picker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PendingPicker', to='order.warehouse')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.reason')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='resend',
            name='packer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ResendPacker', to='order.warehouse'),
        ),
        migrations.CreateModel(
            name='Pending_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.pending')),
            ],
        ),
    ]
