# Generated by Django 3.2.7 on 2022-01-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20211215_0817'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pending_items',
            unique_together={('order', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='resend_items',
            unique_together={('order', 'sku')},
        ),
    ]
