# Generated by Django 3.2.7 on 2022-01-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20220105_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_items',
            name='price',
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pending_items',
            name='shipping',
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resend_items',
            name='price',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resend_items',
            name='shipping',
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
    ]
