# Generated by Django 3.2.7 on 2022-01-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20220105_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='resend',
            name='pending',
        ),
        migrations.AlterField(
            model_name='pending',
            name='order',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
