# Generated by Django 3.2.7 on 2022-01-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20220106_1110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pending_Items',
            new_name='PendingItems',
        ),
    ]
