# Generated by Django 3.2.7 on 2022-01-07 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
        ('order', '0020_rename_pending_items_pendingitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='courier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courier.courier'),
            preserve_default=False,
        ),
    ]
