# Generated by Django 3.2.7 on 2022-01-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_pending_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='original_order',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
