# Generated by Django 3.2.7 on 2022-01-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_pending_original_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingitems',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
