# Generated by Django 3.2.7 on 2022-01-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_pendingitems_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='reason_option',
        ),
        migrations.AddField(
            model_name='pending',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.option'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.option'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resend',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.option'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='return',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.option'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='return',
            name='reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.reason'),
            preserve_default=False,
        ),
    ]
