# Generated by Django 3.2.7 on 2022-01-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20220111_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnitems',
            old_name='original_qty',
            new_name='qty',
        ),
    ]
