# Generated by Django 3.2.7 on 2022-01-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_delete_reason_option'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resend_Items',
            new_name='ResendItems',
        ),
    ]
