# Generated by Django 3.2.7 on 2022-01-13 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_rename_resend_items_resenditems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResendItems',
        ),
    ]
