# Generated by Django 3.2.7 on 2022-01-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_delete_resenditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='resend',
            name='original_order',
            field=models.ForeignKey(default=801351, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resend',
            name='order',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
