# Generated by Django 3.2.7 on 2022-01-19 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_auto_20220118_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resend',
            name='original_order',
        ),
        migrations.AlterField(
            model_name='resend',
            name='order',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True, serialize=False, to='order.order'),
        ),
    ]
