# Generated by Django 3.2.7 on 2022-01-19 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_auto_20220119_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='original_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
    ]
