# Generated by Django 3.2.7 on 2022-02-15 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_warehouse_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimsForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('submitted', models.DateField()),
                ('complete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ClaimsOrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(null=True)),
                ('form', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.claimsforms')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimsResend',
            fields=[
                ('claimsordertype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.claimsordertype')),
                ('resend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.resend')),
            ],
            bases=('order.claimsordertype',),
        ),
        migrations.CreateModel(
            name='ClaimsRefund',
            fields=[
                ('claimsordertype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.claimsordertype')),
                ('refund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.refund')),
            ],
            bases=('order.claimsordertype',),
        ),
    ]
