# Generated by Django 3.2.7 on 2022-02-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_option_claimable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(null=True)),
                ('form', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.claimsforms')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.RemoveField(
            model_name='claimsrefund',
            name='claimsordertype_ptr',
        ),
        migrations.RemoveField(
            model_name='claimsrefund',
            name='refund',
        ),
        migrations.RemoveField(
            model_name='claimsresend',
            name='claimsordertype_ptr',
        ),
        migrations.RemoveField(
            model_name='claimsresend',
            name='resend',
        ),
        migrations.RemoveField(
            model_name='courier_csv',
            name='courier',
        ),
        migrations.DeleteModel(
            name='ClaimsOrderType',
        ),
        migrations.DeleteModel(
            name='ClaimsRefund',
        ),
        migrations.DeleteModel(
            name='ClaimsResend',
        ),
        migrations.DeleteModel(
            name='Courier_Csv',
        ),
    ]
