# Generated by Django 3.2.7 on 2022-03-07 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_auto_20220217_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('created', models.DateField()),
                ('submitted', models.DateField()),
                ('complete', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='claims',
            name='form',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.claimforms'),
        ),
        migrations.DeleteModel(
            name='ClaimsForms',
        ),
    ]
