# Generated by Django 3.2.7 on 2022-03-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_auto_20220307_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimforms',
            name='submitted',
        ),
    ]
