# Generated by Django 3.2.7 on 2022-03-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_auto_20220308_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.claimforms'),
        ),
    ]
