# Generated by Django 3.2.7 on 2022-03-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_alter_claims_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimforms',
            name='created',
            field=models.DateField(),
        ),
    ]
