# Generated by Django 3.2.7 on 2022-03-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_claimforms_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimforms',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
