# Generated by Django 3.2.7 on 2022-03-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_alter_claimforms_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimforms',
            name='actual_payout',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='claimforms',
            name='claim_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimforms',
            name='expected_payout',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
