# Generated by Django 3.2.7 on 2022-03-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_auto_20220321_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
