# Generated by Django 3.2.7 on 2022-03-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_alter_order_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
