# Generated by Django 3.2.7 on 2022-03-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_claimforms_courier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
