# Generated by Django 3.2.7 on 2022-04-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0048_claims_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='accepted_total',
            field=models.FloatField(null=True),
        ),
    ]
